name: IfTheHTTPReferrer
id:   IfTheHTTPReferrer
key:  ifthehttpreferrer
author_name: Alfasado Inc.
author_link: http://alfasado.net/
version: 0.1
description: '<__trans phrase="Conditional Tags MTIfTheHTTPReferrer or MTIfHTTPReferrer.">'
l10n_class: IfTheHTTPReferrer::L10N
tags:
    block:
        IftheHTTPReferrer?: $ifthehttpreferrer::IfTheHTTPReferrer::Tags::hdlr_ifthehttpreferrer
        IftheHTTPReferrer?: $ifthehttpreferrer::IfTheHTTPReferrer::Tags::hdlr_ifthehttpreferrer
